# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    
    App\Domain\Service\NotificationSender:
        arguments:
            $notificationLogger: '@App\Domain\Service\NotificationLogger'

    App\Domain\Service\NotificationLogger:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    Twilio\Rest\Client:
        arguments:
            $username: '%env(TWILIO_SID)%'
            $password: '%env(TWILIO_TOKEN)%'
    
    
    App\Infrastructure\Notification\Adapter\TwilioSmsProviderAdapter:
        arguments:
            $twilioClient: '@Twilio\Rest\Client'
            $twilioPhone: '%env(TWILIO_PHONE_NUMBER)%'
    
    App\Infrastructure\Notification\Adapter\AnotherSmsProviderAdapter: ~
    
    Aws\Ses\SesClient:
        factory: [ 'Aws\Ses\SesClient', 'factory' ]
        arguments:
            -   version: 'latest'
                region: 'your-region'
                credentials:
                    key: '%env(AWS_SES_KEY)%'
                    secret: '%env(AWS_SES_SECRET)%'
    
    App\Infrastructure\Notification\Adapter\AwsSesEmailProviderAdapter:
        arguments:
            $sesClient: '@Aws\Ses\SesClient'

    App\Infrastructure\Notification\Adapter\AnotherEmailProviderAdapter: ~
    
    App\Infrastructure\Notification\Adapter\PushyPushProviderAdapter: ~

    App\Domain\Notification\SmsNotificationProviders:
        arguments:
            $providers:
                - '@App\Infrastructure\Notification\Adapter\TwilioSmsProviderAdapter'
                - '@App\Infrastructure\Notification\Adapter\AnotherSmsProviderAdapter'
    
    App\Domain\Notification\EmailNotificationProviders:
        arguments:
            $providers:
                - '@App\Infrastructure\Notification\Adapter\AwsSesEmailProviderAdapter'
                - '@App\Infrastructure\Notification\Adapter\AnotherEmailProviderAdapter'
                    
    App\Domain\Notification\PushNotificationProviders:
        arguments:
            $providers:
                - '@App\Infrastructure\Notification\Adapter\PushyPushProviderAdapter'




    App\Cli\NotificationCli:
        arguments:
            $cliHandler: '@App\Application\Handler\CliHandler'
        tags: ['console.command']

    App\Application\Handler\CliHandler:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $notificationService: '@App\Application\Service\NotificationService'

    App\Application\Service\NotificationInfoService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
